baseURL = "https://caffeine-fighter.github.io"
languageCode = "ko-kr"
defaultContentLanguage = "ko"
title = "카페인파이터의 일기장"

[module]
  [[module.imports]]
    path = "github.com/CaiJimmy/hugo-theme-stack/v4"

# robots.txt
enableRobotsTXT = true

# sitemap 생성
[sitemap]
# always, hourly daily, weekly, monthly, yearly, never
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

[params]
  math = true

  [params.search]
    enabled = true

  [params.sidebar]
    subtitle = "Data Science, Mathematics & Algorithms"
    [params.sidebar.avatar]
      local = true
      src = "img/hoshino_test.jpg"


[[menu.main]]
  identifier = "home"
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  identifier = "archives"
  name = "Archives"
  url = "/archives/"
  weight = 2

[[menu.main]]
  identifier = "categories"
  name = "Categories"
  url = "/categories/"
  weight = 3

[[menu.main]]
  identifier = "search"
  name = "Search"
  url = "/search/"
  weight = 4

