# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
    identifier = "github"
    name       = "GitHub"
    url        = "https://github.com/caffeine-fighter"

    [social.params]
        icon = "brand-github"

[[social]]
    identifier = "X"
    name       = "X"
    url        = "https://x.com/pstr31"
    [social.params]
        icon = "brand-x"
