# Pages placed under these sections will be shown on homepage and archive page.
mainSections = ["post"]
# Output page's full content in RSS.
rssFullContent = true
favicon        = "img/favicon.png"

# Accepted values: "default", "lastmod"
# default = see https://gohugo.io/quick-reference/glossary/#default-sort-order
# lastmod = sort by last modified date, in descending order
SortBy              = "default"

[footer]
    since      = 2026
    customText = ""

[dateFormat]
    published   = ":date_full"
    lastUpdated = ":date_full"

[sidebar]
    emoji    = ""
    subtitle = "SNU TI & Math & Music 24"
    avatar   = "img/hoshino_test_resized.jpg"

[article]
    headingAnchor = false
    math          = true
    readingTime   = true

    [article.license]
        enabled = true
        default = "Licensed under CC BY-NC-SA 4.0"

[widgets]
    homepage = [
        { type = "search" },
        { type = "archives", params = { limit = 5 } },
        { type = "categories", params = { limit = 10 } },
        { type = "tag-cloud", params = { limit = 10 } },
    ]
    page = [{ type = "toc" }]

[opengraph.twitter]
    site = ""
    card = "summary_large_image"

[colorScheme]
    toggle  = true
    default = "auto"

[comments]
    enabled  = true
    provider = "giscus" 

    [comments.giscus]
        repo = "caffeine-fighter/caffeine-fighter.github.io"
        repoId = "R_kgDORaF3hg"
        category = "Announcements"
        categoryId = "DIC_kwDORaF3hs4C3cX0"
        mapping = "pathname"
        strict = "0"
        reactionsEnabled = "1"
        emitMetadata = "0"
        inputPosition = "bottom"
        lightTheme = "noborder_light"
        darkTheme = "noborder_gray"
        lang = "ko"
        loading = "lazy"
        crossorigin = "anonymous"